# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - node/install-packages: 
          pkg-manager: yarn
      - run:
          name: Run tests
          command: $(yarn bin)/cypress run --record  --key <record_key>

workflows:
  sample: 
    jobs:
      - build-and-test
